import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Sparkles, RefreshCw } from 'lucide-react'
import api from '../../lib/api'

interface Insight {
  insight: string
  asOf: string
}

export default function InsightsPanel() {
  const qc = useQueryClient()
  const [refreshing, setRefreshing] = useState(false)

  const q = useQuery<Insight>({
    queryKey: ['insights'],
    queryFn: async () => (await api.get('/insights')).data,
    staleTime: 1000 * 60 * 60, // server caches per day; don't refetch each mount within the hour
    retry: 0,
  })

  async function refresh() {
    setRefreshing(true)
    try {
      const { data } = await api.get('/insights?refresh=1')
      qc.setQueryData(['insights'], data)
    } catch {
      // leave the current insight in place
    } finally {
      setRefreshing(false)
    }
  }

  const busy = q.isFetching || refreshing

  return (
    <section
      style={{
        position: 'relative',
        borderRadius: 18,
        padding: 22,
        background: 'linear-gradient(135deg, rgba(34,227,138,0.10), rgba(155,124,255,0.10))',
        border: '1px solid rgba(155,124,255,0.22)',
        overflow: 'hidden',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 10 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
          <Sparkles className="h-4 w-4" style={{ color: '#9B7CFF' }} />
          <span style={{ fontFamily: "'Space Grotesk'", fontSize: 15, fontWeight: 700, letterSpacing: -0.2 }}>AI insights</span>
        </div>
        <button
          onClick={refresh}
          disabled={busy}
          title="Regenerate"
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            border: '1px solid rgba(255,255,255,0.12)',
            background: 'rgba(255,255,255,0.05)',
            color: busy ? '#5B6172' : '#8A90A2',
            borderRadius: 9,
            padding: '5px 10px',
            fontSize: 12,
            fontWeight: 600,
            fontFamily: 'inherit',
            cursor: busy ? 'default' : 'pointer',
          }}
        >
          <RefreshCw className={busy ? 'h-3.5 w-3.5 animate-spin' : 'h-3.5 w-3.5'} />
          Refresh
        </button>
      </div>

      {q.isLoading || refreshing ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {[92, 84, 60].map((w) => (
            <div key={w} style={{ height: 12, width: `${w}%`, borderRadius: 6, background: 'rgba(255,255,255,0.06)' }} />
          ))}
        </div>
      ) : q.isError ? (
        <div style={{ fontSize: 13.5, color: '#8A90A2' }}>Insights are unavailable right now — try Refresh in a moment.</div>
      ) : (
        <>
          <p style={{ margin: 0, fontSize: 14.5, lineHeight: 1.6, color: '#E7EAF1' }}>{q.data?.insight}</p>
          <div style={{ marginTop: 10, fontSize: 11, color: '#8A90A2' }}>
            Generated by Gemini · {q.data?.asOf}
          </div>
        </>
      )}
    </section>
  )
}
