-- AlterTable
ALTER TABLE "ProjectionSettings" ADD COLUMN     "annualSpending" DOUBLE PRECISION NOT NULL DEFAULT 60000,
ADD COLUMN     "currentAge" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "endAge" INTEGER NOT NULL DEFAULT 95,
ADD COLUMN     "pensionAnnual" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pensionStartAge" INTEGER NOT NULL DEFAULT 65,
ADD COLUMN     "retirementAge" INTEGER NOT NULL DEFAULT 55,
ADD COLUMN     "socialSecurityAnnual" DOUBLE PRECISION NOT NULL DEFAULT 24000,
ADD COLUMN     "ssStartAge" INTEGER NOT NULL DEFAULT 67,
ADD COLUMN     "taxRatePct" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN     "vacationBudget" DOUBLE PRECISION NOT NULL DEFAULT 12000,
ADD COLUMN     "vacationYears" INTEGER NOT NULL DEFAULT 10;
